# FIXME: rubocop-rspec rules, will be clarified with team
# Offense count: 29
RSpec/AnyInstance:
  Enabled: false

# Offense count: 201
# Configuration parameters: Prefixes.
# Prefixes: when, with, without
RSpec/ContextWording:
  Enabled: false

# Offense count: 173
# Configuration parameters: Max.
RSpec/ExampleLength:
  Max: 20

# Offense count: 13
RSpec/ExpectInHook:
  Exclude:
    - 'spec/graph_ql/account/sign_in_spec.rb'
    - 'spec/services/bet_external_validation/service_spec.rb'
    - 'spec/services/odds_feed/radar/entities/competitor_loader_spec.rb'
    - 'spec/services/odds_feed/radar/entities/player_loader_spec.rb'
    - 'spec/services/odds_feed/radar/entities/venue_loader_spec.rb'
    - 'spec/services/odds_feed/radar/market_generator/template_loader_spec.rb'

# Offense count: 69
# Configuration parameters: EnforcedStyle.
# SupportedStyles: have_received, receive
RSpec/MessageSpies:
  Enabled: false

# Offense count: 137
# Configuration parameters: AggregateFailuresByDefault.
RSpec/MultipleExpectations:
  Max: 9

# Offense count: 345
RSpec/NamedSubject:
  Enabled: false

# Offense count: 38
RSpec/NestedGroups:
  Max: 5

# end rubocop-rspec rules

require: rubocop-rspec

Bundler/OrderedGems:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/Lambda:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 13

Metrics/BlockLength:
  Enabled: false

AllCops:
  Exclude:
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'db/schema.rb'
    - 'db/migrate/20180515113514_devise_create_customers.rb'
    - 'db/migrate/20180521120705_devise_create_users.rb'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
