inherit_from: .rubocop_todo.yml

require: rubocop-rspec

Bundler/OrderedGems:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/Lambda:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/MethodLength:
  Max: 13

Metrics/BlockLength:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/features/*'

AllCops:
  Exclude:
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'db/schema.rb'
    - 'db/migrate/20180515113514_devise_create_customers.rb'
    - 'db/migrate/20180521120705_devise_create_users.rb'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'tmp/**/*'
