Style/FrozenStringLiteralComment:
  Enabled: false

Bundler/OrderedGems:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'node_modules/**/*'
