version: '3.1'

services:

  db:
    image: postgres:10.3-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - .:/arcanebet
    ports:
      - "3000:3000"
    depends_on:
      - db
