common: &default_settings
license_key: <%= ENV['NEWRELIC_KEY'] %>
  app_name: Arcanebet Backend
  log_level: info

development:
  <<: *default_settings
  app_name: Arcanebet Backend (development)
  monitor_mode: false

test:
  <<: *default_settings
  monitor_mode: false

production:
  <<: *default_settings
