common: &default_settings
  license_key: <%= ENV['NEWRELIC_KEY'] %>
  log_level: info

development:
  <<: *default_settings
  app_name: ArcaneBet Backend (Development)
  monitor_mode: false

test:
  <<: *default_settings
  app_name: ArcaneBet Backend (Test)
  monitor_mode: false

production:
  <<: *default_settings
  app_name: <%= ENV['NEWRELIC_ENV'] == 'production' ? 'ArcaneBet Production' : 'ArcaneBet Staging' %>
  monitor_mode: true

