:concurrency: 1
:queues:
  - radar_odds_feed_high
  - radar_odds_feed_low
  - radar_missing_heartbeat

:schedule:
  missing_heartbeat_check:
    include_metadata: true
    every: <%= ENV.fetch('MISSING_HEARTBEAT_CHECK_INTERVAL', '20s') %>
    class: Radar::MissingHeartbeatWorker
    enabled: <%= ['production', 'staging'].include?(ENV['RACK_ENV']) %>
    description: "Checks if any Radar producers connection status expired and sends recovery requests"
