:concurrency: 1
:queues:
  - radar_odds_feed_high
  - radar_odds_feed_low
  - radar_missing_heartbeat

:schedule:
  missing_heartbeat_check:
    include_metadata: true
    every: <%= ENV.fetch('MISSING_HEARTBEAT_CHECK_INTERVAL', '15s') %>
    class: Radar::MissingHeartbeatWorker
    enabled: true
    description: "Checks if any Radar producers connection status expired"
