:queues:
  - critical
  - mq
  - default
  - expired_live
  - expired_prematch

:schedule:
  check_bet_expirasy_live:
    every: <%= "#{ENV.fetch('MTS_LIVE_VALIDATION_TIMEOUT') { 10 }}s" %>
    class: Scheduled::ExpiringLiveWorker
    queue: expired_live

  check_bet_expirasy_prematch:
    every: <%= "#{ENV.fetch('MTS_PREMATCH_VALIDATION_TIMEOUT') { 3 }}s" %>
    class: Scheduled::ExpiringPrematchWorker
    queue: expired_prematch
