:queues:
  - critical
  - mq
  - default
  - market_templates_update
  - expired_live
  - expired_prematch

:schedule:
  regular_market_templates_update:
    cron: <%= "#{ENV.fetch('MARKET_TEMPLATES_UPDATE_CRON') { '0 20 * * 6' }}" %>
    class: Radar::MarketsUpdateWorker
    queue: market_templates_update

  unpopular_live_events_clean_worker:
    cron: <%= "#{ENV.fetch('UNPOPULAR_LIVE_EVENTS_CLEANER_CRON') { '0 * * * *' }}" %>
    class: UnpopularLiveEventsCleanWorker

  unpopular_pre_live_events_clean_worker:
    cron: <%= "#{ENV.fetch('UNPOPULAR_PRE_LIVE_EVENTS_CLEANER_CRON') { '0 * * * *' }}" %>
    class: UnpopularPreLiveEventsCleanWorker

  check_bet_expirasy_live:
    every: <%= "#{ENV.fetch('MTS_LIVE_VALIDATION_TIMEOUT') { 10 }}s" %>
    class: Scheduled::ExpiringLiveWorker
    queue: expired_live

  check_bet_expirasy_prematch:
      every: <%= "#{ENV.fetch('MTS_PREMATCH_VALIDATION_TIMEOUT') { 3 }}s" %>
      class: Scheduled::ExpiringPrematchWorker
      queue: expired_prematch
