:queues:
  - critical
  - mq
  - default
  - market_templates_update

:schedule:
  regular_market_templates_update:
    cron: <%= "#{ENV.fetch('MARKET_TEMPLATES_UPDATE_CRON') { '0 20 * * 6' }}" %>
    class: Radar::MarketsUpdateWorker
    queue: market_templates_update
