:queues:
  - critical
  - mq
  - default

:schedule:
  unpopular_events_clean_worker:
    cron: <%= "#{ENV.fetch('UNPOPULAR_EVENTS_CLEANER_CRON') { '0 * * * *' }}" %>
    class: UnpopularEventsCleanWorker
