:queues:
  - critical
  - mq
  - default
  - market_templates_update

:schedule:
  pre_match_markets_close_worker:
    cron: <%= "#{ENV.fetch('PRE_MATCH_MARKET_CLOSE_CRON') { '*/15 * * * * *' }}" %>
    class: PreMatchMarketsCloseWorker
  regular_market_templates_update:
    cron: <%= "#{ENV.fetch('MARKET_TEMPLATES_UPDATE_CRON') { '0 20 * * 6' }}" %>
    class: Radar::MarketsUpdateWorker
    queue: market_templates_update
  unpopular_live_events_clean_worker:
    cron: <%= "#{ENV.fetch('UNPOPULAR_LIVE_EVENTS_CLEANER_CRON') { '0 * * * *' }}" %>
    class: UnpopularLiveEventsCleanWorker
  unpopular_pre_live_events_clean_worker:
    cron: <%= "#{ENV.fetch('UNPOPULAR_PRE_LIVE_EVENTS_CLEANER_CRON') { '0 * * * *' }}" %>
    class: UnpopularPreLiveEventsCleanWorker
