:queues:
  - critical
  - mq
  - default

:schedule:
  pre_match_markets_close_worker:
    cron: <%= "#{ENV.fetch('PRE_MATCH_MARKET_CLOSE_CRON') { '*/15 * * * * *' }}" %>
    class: PreMatchMarketsCloseWorker
  unpopular_live_events_clean_worker:
    cron: <%= "#{ENV.fetch('UNPOPULAR_LIVE_EVENTS_CLEANER_CRON') { '0 * * * *' }}" %>
    class: UnpopularLiveEventsCleanWorker
  unpopular_pre_live_events_clean_worker:
    cron: <%= "#{ENV.fetch('UNPOPULAR_PRE_LIVE_EVENTS_CLEANER_CRON') { '0 * * * *' }}" %>
    class: UnpopularPreLiveEventsCleanWorker
